
services:
  # ASP.net Core API services
  backend:
    container_name: LinkNest.backend
    build: 
      context: ./Backend/Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=3000
        - ASPNETCORE_HTTPS_PORTS=3001
        - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/backend.pfx
        - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    volumes:
      - ./Backend/Backend/certs:/https:ro ## it's basically <host_path>:<container_path>:<options>

    depends_on:
      db:
        condition:  service_healthy
    networks:
      - app-network


  #frontend Serives
  frontend:
    container_name: LinkNest.frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network



  # Database
  db:
    container_name: LinkNest.db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - sql_data:/var/opt/mssql       # Persistent DB storage

 
    networks:
      - app-network
    healthcheck:
     ## test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${SA_PASSWORD}' -Q \"SELECT 1\" -b -o /dev/null"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s



  grafana:
    container_name: LinkNest.grafana
    image: grafana/grafana
    ports:
      - "3002:3000"  # Host 3002 → Container 3000 (Grafana's default UI port)
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - app-network

  prometheus:
    container_name: LinkNest.prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Backend/Backend/prom/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - app-network


#  Shared named volumes (DB persistence)
volumes:
  sql_data:
  grafana_data:


#  Shared network so containers can reach each other by name
networks:
  app-network:
    driver: bridge
